force-app/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Character__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>The age of your character</description>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Charisma__c.field-meta.xml
<CustomField>
    <fullName>Charisma__c</fullName>
    <description>This determines how well you get along and communicate with others.</description>
    <label>Charisma</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Character_Classes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Constitution__c.field-meta.xml
<CustomField>
    <fullName>Constitution__c</fullName>
    <label>Constitution</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This holds as a description for your character.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Dexterity__c.field-meta.xml
<CustomField>
    <fullName>Dexterity__c</fullName>
    <label>Dexterity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Eye_Color__c.field-meta.xml
<CustomField>
    <fullName>Eye_Color__c</fullName>
    <label>Eye Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Character_Genders</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Hair_Color__c.field-meta.xml
<CustomField>
    <fullName>Hair_Color__c</fullName>
    <label>Hair Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Intelligence__c.field-meta.xml
<CustomField>
    <fullName>Intelligence__c</fullName>
    <description>This is how smart and intellectual your character is.</description>
    <label>Intelligence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <description>Pick a race for your D&amp;D Character</description>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Character_Races</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Select_Eye_Color__c.field-meta.xml
<CustomField>
    <fullName>Select_Eye_Color__c</fullName>
    <label>Select Eye Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Select_Hair_Color__c.field-meta.xml
<CustomField>
    <fullName>Select_Hair_Color__c</fullName>
    <label>Select Hair Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Bluish</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Golden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Strength__c.field-meta.xml
<CustomField>
    <fullName>Strength__c</fullName>
    <description>The strength of your character</description>
    <label>Strength</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Character__c/fields/Wisdom__c.field-meta.xml
<CustomField>
    <fullName>Wisdom__c</fullName>
    <description>This determines how wise your character is.</description>
    <label>Wisdom</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Character_Classes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BARBARIAN</fullName>
    </customValue>
    <customValue>
        <fullName>BARD</fullName>
    </customValue>
    <customValue>
        <fullName>CLERIC</fullName>
    </customValue>
    <customValue>
        <fullName>DRUID</fullName>
    </customValue>
    <customValue>
        <fullName>FIGHTER</fullName>
    </customValue>
    <customValue>
        <fullName>MONK</fullName>
    </customValue>
    <customValue>
        <fullName>PALADIN</fullName>
    </customValue>
    <customValue>
        <fullName>RANGER</fullName>
    </customValue>
    <customValue>
        <fullName>ROGUE</fullName>
    </customValue>
    <customValue>
        <fullName>SORCERER</fullName>
    </customValue>
    <customValue>
        <fullName>WARLOCK</fullName>
    </customValue>
    <customValue>
        <fullName>WIZARD</fullName>
    </customValue>
    <masterLabel>Character Classes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Character_Genders.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Character Genders</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Character_Races.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AARAKOCRA</fullName>
    </customValue>
    <customValue>
        <fullName>AASIMAR</fullName>
    </customValue>
    <customValue>
        <fullName>DRAGONBORN</fullName>
    </customValue>
    <customValue>
        <fullName>DWARF</fullName>
    </customValue>
    <customValue>
        <fullName>ELF</fullName>
    </customValue>
    <customValue>
        <fullName>GENASI</fullName>
    </customValue>
    <customValue>
        <fullName>GNOME</fullName>
    </customValue>
    <customValue>
        <fullName>GOLIATH</fullName>
    </customValue>
    <customValue>
        <fullName>HALF-ELF</fullName>
    </customValue>
    <customValue>
        <fullName>HALFLING</fullName>
    </customValue>
    <customValue>
        <fullName>HALF-ORC</fullName>
    </customValue>
    <customValue>
        <fullName>HUMAN</fullName>
    </customValue>
    <customValue>
        <fullName>TIEFLING</fullName>
    </customValue>
    <masterLabel>Character Races</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CharacterTriggerHelper.cls
public class CharacterTriggerHelper {
    public static void randomize(List<Character__c> charList) {
        
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
        String name = '';
        while (name.length() < 7) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            name += chars.substring(idx, idx+1);
        }
        
        for (Character__c c: charList) {
            if(c.Name==null) {
                c.Name = name;
            }
            if(c.Strength__c == null){
                c.Strength__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Dexterity__c == null){
                c.Dexterity__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Constitution__c == null){
                c.Constitution__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Intelligence__c == null){
                c.Intelligence__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Wisdom__c == null){
                c.Wisdom__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Charisma__c == null){
                c.Charisma__c = Integer.valueOf(math.random()*10);               
            }
            if(c.Age__c == null){
                c.Age__c = Integer.valueOf(math.random()*800);               
            }
            
            if (c.Hair_Color__c == null) {
                Schema.DescribeFieldResult fieldResult = Character__c.Select_Hair_Color__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> hairColors = new List<String>();
                for(Schema.PicklistEntry pp:ple) {
                    hairColors.add(pp.getValue());
                }
                c.Select_Hair_Color__c = hairColors[Integer.valueOf(math.random()*(hairColors.size() -  1))];
                c.Hair_Color__c = c.Select_Hair_Color__c;
            }
            
            if (c.Select_Eye_Color__c == null) {
                Schema.DescribeFieldResult fieldResult = Character__c.Select_Eye_Color__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> eyeColors = new List<String>();
                for(Schema.PicklistEntry pp:ple) {
                    eyeColors.add(pp.getValue());
                }
                c.Select_Eye_Color__c = eyeColors[Integer.valueOf(math.random()*(eyeColors.size() -  1))];
                c.Eye_Color__c = c.Select_Eye_Color__c;
            }
            
            if (c.Class__c == null) {
                Schema.DescribeFieldResult fieldResult = Character__c.Class__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> classes = new List<String>();
                for(Schema.PicklistEntry pp:ple) {
                    classes.add(pp.getValue());
                }
                c.Class__c = classes[Integer.valueOf(math.random()*(classes.size() -  1))];
            }
            
            if (c.Gender__c == null) {
                Schema.DescribeFieldResult fieldResult = Character__c.Gender__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> genders = new List<String>();
                for(Schema.PicklistEntry pp:ple) {
                    genders.add(pp.getValue());
                }
                c.Gender__c = genders[Integer.valueOf(math.random()*(genders.size() -  1))];
            }
            
            if (c.Race__c == null) {
                Schema.DescribeFieldResult fieldResult = Character__c.Race__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> races = new List<String>();
                for(Schema.PicklistEntry pp:ple) {
                    races.add(pp.getValue());
                }
                c.Race__c = races[Integer.valueOf(math.random()*(races.size() -  1))];
            }
            
            if (c.Description__c == null) {
                c.Description__c = backstoryGenerator.getStory(c.Name, c.Class__c);
            }
        }  
    }
}